################################################################################
# Tool Configuration

[tool.ruff]
target-version = "py38"
line-length = 120

[tool.ruff.lint]
select = [
    "PL",       # pylint
    "E", "W",   # pycodestyle
    "F",        # pyflakes
    "C90",      # mccabe
    "I",        # isort
    "N",        # pep8-naming
    "D",        # pydocstyle
    "UP",       # pyupgrade
    "TRY",      # tryceratops
    "ANN",      # flake8-annotations
    "S",        # flake8-bandit
    "B",        # flake8-bugbear
    "C4",       # flake8-comprehensions
    "FA",       # flake8-future-annotations
    "G",        # flake8-logging-format
    "PIE",      # flake8-pie
    "SIM",      # flake8-simplify
    "TCH",      # flake8-type-checking
    "ARG",      # flake8-unused-arguments
    "PTH",      # flake8-use-pathlib
    "RUF",      # ruff-specific rules
]
ignore = [
    "ANN101", "ANN102",     # type checkers infer the type of `self`/`cls` automatically
    "TRY003",   # allow formatting exception messages
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.black]
line-length = 120
fast = false  # Check that the code is semantically equivalent before and after reformatting
skip-string-normalization = true  # Don't convert to double quotes
color = true
